# Generated by Django 5.2.4 on 2025-09-21 09:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenseapp', '0002_expensecategorymodel_expensemanagemodel_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExpenseManageModel',
            new_name='ExpenseModel',
        ),
    ]
